version: "3"
services:
  predictor:
    image: predictor:latest
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "api.py"
      FLASK_ENV: "development"
      FLASK_DEBUG: "True"
